// Copyright June Rhodes. All Rights Reserved.

#pragma once

#if defined(UE_5_0_OR_LATER)
#define EOS_PARTY_SYSTEM_HAS_QUERY_PARTY_JOINABILITY_EX 1
#define EOS_PARTY_SYSTEM_HAS_RESPOND_TO_QUERY_JOINABILITY 1
#define EOS_CONFIG_REQUIRES_MODERN_ITERATION 1
#define EOS_PARTY_SYSTEM_REQUEST_TO_JOIN_PARTY 1
#endif

#if defined(UE_4_27_OR_LATER)
#define EOS_PARTY_SYSTEM_HAS_QUERY_PARTY_JOINABILITY_EX 1
#define EOS_PARTY_SYSTEM_HAS_RESPOND_TO_QUERY_JOINABILITY 1
#define EOS_SESSION_HAS_LOBBY_OPTIONS 1
#endif